version: "3.9"

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    restart: on-failure:0
    ports:
     - "8080:8080"
     - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/data"
      ENABLE_MODULES: text2vec-huggingface
      DEFAULT_VECTORIZER_MODULE: text2vec-huggingface
    volumes:
      - weaviate_data:/data  # Use named volume for Weaviate data persistence
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: app
    command: "./dev_start.sh"
    ports:
      - "8000:8000"  
    volumes:
      - ./api:/app  # Mount the api directory to the container
      - api_data:/app/data  # Use named volume for app data persistence
    env_file:
    - ./secrets/.env
    # - ./secrets/.env.db
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    # env_file:
    #   - secrets/.env.db
    volumes:
      - mongo_data:/data/db  # Use named volume for MongoDB data persistence
    networks:
      - app-network
    restart: unless-stopped

  celery_worker:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: celery_worker
    command: ["celery", "-A", "src.core.celery_config.celery_app", "worker", "--loglevel=info"]
    volumes:
      - ./api:/app  # Mount the api directory to the container
      - api_data:/app/data  # Use named volume for app data persistence
    env_file:
    - ./secrets/.env
    depends_on:
      - redis
      - weaviate
      - app 
      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  weaviate_data:
  api_data:

